AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  docker-selenium-lambda sample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  SeleniumDemo:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 2048
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

